spring:
  application:
    name: elasticsearch-demo
  elasticsearch:
    rest:
      uris: localhost:9200

server:
  port: 8090
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 4096